### ISSUE TITLE
RPC update & Memory Allocation

### ISSUE THREAD

**Issue by Chayotea** [ShayBox/VRC-LOG#3]
Pretty much after the 0.5.1 "RPC update" a few weeks ago VRC-LOG refuses to authenticate. I hope it is not just me as I have been trying quite a few times and even reinstalling discord. Currently running 0.5.0 so far has been my only solution.

VRC-LOG closes due to 32bit memory allocation limit. Most likely do to me having monster sized >200gb VRChat cache.

**Comment by ShayBox** [comment]
If you have a 32bit memory allocation limit does that mean you're using 32bit Windows? I use a 1TB dedicated cache drive but I'm on Windows 11 64bit.

**Comment by ShayBox** [comment]
0.5.5 Fixed Discord RPC https://github.com/ShayBox/VRC-LOG/releases/tag/0.5.5

The memory allocation limit crash is weird, do you have a log and can you look at memory usage before it crashes?

**Comment by Chayotea** [comment]
Maybe it is a malformed avatar as memory usage was not very high in task manager. VRC-LOG simply outputting "failed to allocate" then what I assume is the max memory it can allocate in bytes since it is a 32bit program. I'm on 64bit Windows. So far been running 0.5.5 and it been fine. I try to see what I can find if it happens again.

**Comment by Chayotea** [comment]
Here we go after a few days it happened again.
![image](https://github.com/ShayBox/VRC-LOG/assets/82981665/1316a8a3-c657-4f43-b8d9-0137ebe2c53c)

**Comment by ShayBox** [comment]
Interesting, I haven't seen it use that much memory before, I'm not sure it should be able to.

I've used an entire 500GB hard drive as my cache drive before and didn't have any issue, but I haven't tried it recently.

**Comment by Chayotea** [comment]
I first used VRC-LOG but due to this I switched to ravenwood logger. Well ravenwood is dead. The only problem that I had with ravenwood was that if you told it yes to scan the entire cache it would consume more than 20gb ram. I only have 32gb so my system would crawl as it was starting to use the pagefile.

**Comment by ShayBox** [comment]
Are you using an SSD for your cache?

**Comment by Chayotea** [comment]
Cache is a pair of drives in RAID 0... that I made in 2013. If it works don't fix it lol but yea I may be pushing it now.

**Comment by ShayBox** [comment]
It might be that your cache is so fast it's filling the buffer way faster than it can empty, I'll do some testing on my SSD and see if I can replicate it and do anything about it.

**Comment by Chayotea** [comment]
BIt strange because I expected it to be slow 
![image](https://github.com/ShayBox/VRC-LOG/assets/82981665/77312581-c6ce-46d1-91a0-82d44e51886f)

**Comment by Chayotea** [comment]
I found the problem. After an hour of cutting up my cache it comes down to just one file! It is nothing more than just one very large world. https://vrchat.com/home/world/wrld_7d2af18c-e4a1-4084-9cd2-b27432b45980

**Comment by ShayBox** [comment]
Good catch, Mine peaks at 1.7g reading that file but doesn't crash. It's because it was reading the entire file into memory before parsing it, I've changed it to stream the file line by line instead. It doesn't seem to use anywhere near as much memory now.

https://github.com/ShayBox/VRC-LOG/releases/tag/0.5.6

**Comment by Chayotea** [comment]
Hum after a hour of testing 0.5.6 tops out at .1MB/s disk usage. I guess it is working at a incredibly slow speed. 
Meanwhile immediately opening 0.5.5 after a few minutes is already printing out id's and reading at 100-200MB/s

**Comment by ShayBox** [comment]
Ah okay I missed that it wasn't reading most of the data files because of non-utf-8 bytes, I switched it to read byte by byte instead.

It probably won't be as fast as 0.5.5 but it shouldn't matter because of the limited submission speed, it still takes longer to submit than to read the cache.

https://github.com/ShayBox/VRC-LOG/releases/tag/0.5.6
