### ISSUE TITLE
Doesn't upload previously private

### ISSUE THREAD

**Issue by Anthonyg5005** [ShayBox/VRC-LOG#5]
if it already attempted to upload an id and the avatar was private it won't upload even if made public later on. Not sure how easy this would be to fix without sending a put request for all cached avatars again, even if they are already in the DB.

**Comment by ShayBox** [comment]
Currently, VRCDB doesn't re-check avatars, so re-sending after sending it as private wouldn't do anything, if they add a re-check cooldown interval I'll add a last checked column to the cache for re-submission.

**Comment by ShayBox** [comment]
The database now re-checks submitted avatars, I am working on and will be releasing an update within a day or two to solve this.

**Comment by Anthonyg5005** [comment]
Awesome

**Comment by ShayBox** [comment]
https://github.com/ShayBox/VRC-LOG/releases/tag/0.5.9

**Comment by ShayBox** [comment]
There can't be duplicate entries because of the unique primary column, I must have gotten the check to see if it's in the cache wrong. I'll push an update to fix it.

I can't check to see if the avatar was private and is now public, that's only checked by the database, all I can do is re-submit to the database for it to check again after X days.

**Comment by ShayBox** [comment]
I have re-released the last update https://github.com/ShayBox/VRC-LOG/releases/tag/0.5.9

I have changed the migration behavior to randomize the existing cache between 0–31 days, so there's not a large burst after updating. If you'd like to use that behavior, you can manually delete the `updated_at` column (not just the data in the rows) from your local database, and it will be re-created with randomized dates. You don't have to do that, it should go through and handle all the NULL columns.

**Comment by Anthonyg5005** [comment]
alright thanks, I'll check it out.

**Comment by Anthonyg5005** [comment]
seems like it still uploads the same id multiple times if you don't remove the nulls from the previous version, which is only a problem if anyone else updated before the fix. Also if you run without the db file it'll create an empty avatars.sqlite file and it won't start and give the following error:\
`Error: no such table: avatars (code 1)`\
sorry for creating more problems for you with this.

**Comment by ShayBox** [comment]
It's alright, if there are bugs I want to fix them. There was a syntax error from an extra comma in the creation statement, and I was only updating the NULL columns if the column didn't exist, now it updates them every time.

https://github.com/ShayBox/VRC-LOG/releases/tag/0.5.9
If there's any more bugs let me know, I think I tested everything.

**Comment by Anthonyg5005** [comment]
it'll upload the first id then give out an error, same result when letting it create a new avatars.sqlite
![image](https://github.com/ShayBox/VRC-LOG/assets/43303671/140ed7c8-5e91-4e80-bf80-6b5e305d72d4)

**Comment by ShayBox** [comment]
Ah, that's unfortunate. I missed an `id (?)` in the send statement. https://github.com/ShayBox/VRC-LOG/releases/tag/0.5.9

**Comment by Anthonyg5005** [comment]
I deleted the avatars.sqlite to create a new one and it works well now. Haven't tested with previous files but the only problem I see is that it seems to take longer on startup to continue uploading ids the larger the db file is which is kind of expected with the extra db info and shouldn't really be a problem if it stays open in the background. another thing I see is that it isn't printing the discord username anymore which I don't really know what that was for anyways, I assume some kind of discord leaderboard. overall seems to work now, if you think it's good you can close this issue unless there's something else you want to improve. Thanks

**Comment by ShayBox** [comment]
I forgot to re-enable VRCDB and cooldown, it's slow because there's an intentional 3s cooldown to prevent hitting the rate limit. https://github.com/ShayBox/VRC-LOG/releases/tag/0.6.0

**Comment by Anthonyg5005** [comment]
Yeah I was confused why it was trying to send so many at a fast speed. seems all good now though, hopefully nothing breaks in a month. thanks for this.
