### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by Chayotea** [ShayBox/VRC-LOG#8]
Tried quite a few times but yea Discord RPC seems broken again on 0.8.0. 
0.7.1 never fails after opening a few times.

**Comment by ShayBox** [comment]
I see, I cloned the user before the sleep/wait for Discord to ready.  
https://github.com/ShayBox/VRC-LOG/releases/tag/0.8.2

**Comment by Chayotea** [comment]
Looks like all is good now. Another discord issue I recently noticed is the readme the invite link for the new providers is invalid. I was curiously trying to find out why NekoSuneVR is running 2 separate databases.

**Comment by ShayBox** [comment]
I updated the [Discord](https://discord.gg/qtwbB2V3n9) links, its 3 separate people but I believe they share or Neko hosts separate instances for them.
